# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 30
    port: 8110

# spring
spring:
    application:
      name: insurance

    profiles:
      active: test

    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false

    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

    http:
      multipart:
        max-file-size: 100MB
        max-request-size: 120MB


# Mybatis
mybatis:
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis.xml



