spring:
    # mysql
    datasource:
        url: jdbc:mysql://localhost:3306/insurance?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: caoyy
        driverClassName: com.mysql.jdbc.Driver

    #AMQP
    rabbitmq:
        host: 192.168.102.17
        port: 5672
        username: guest
        password: guest

insurance:
    res:
      image:
        storage:
          path:
            bill: /Users/caoyangyang/caoyy/server_workspace/insurance/insurance-res/pic/bill
            scooter: /Users/caoyangyang/caoyy/server_workspace/insurance/insurance-res/pic/scooter
        request:
          url:
            prefix: http://localhost/insurance/res/

remote:
    url:
     order: http://192.168.102.17:19606
     ebike: http://192.168.102.16:19602

order:
    generative:
      day:
       limit: 90